application:
  name: deck-cloud-with-kotlin
  project: ktor_prez
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: deck-cloud-with-kotlin
    paths:
    - /*
